/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type VideoChunk = {
  _type: "videoChunk";
  startSeconds?: number;
  text?: string;
};

export type VideoChapter = {
  _type: "videoChapter";
  startSeconds?: number;
  label?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Resource = {
  _type: "resource";
  type?: "pdf" | "link" | "code" | "other";
  title?: string;
  description?: string;
  url?: string;
};

export type Progress = {
  _id: string;
  _type: "progress";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  completedLessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
  resumePositions?: Array<{
    lesson?: LessonReference;
    position?: number;
    _key: string;
  }>;
};

export type AgentContext = {
  _id: string;
  _type: "agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contentScope?: string;
  instructions?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  url?: string;
  chapters?: Array<
    {
      _key: string;
    } & VideoChapter
  >;
  chunks?: Array<
    {
      _key: string;
    } & VideoChunk
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoChunk
  | VideoChapter
  | LearningOutcome
  | LessonReference
  | Module
  | Resource
  | Progress
  | AgentContext
  | Video
  | SanityImageAssetReference
  | InstructorReference
  | CategoryReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Lesson
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course"] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    price,    popular,    studentCount,    category->{ title, "slug": slug.current },    instructor->{ name, "slug": slug.current, photo }  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  instructor: {
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    ...,    instructor->,    category->,    modules[] {      ...,      lessons[]-> {        ...,      }    }  }
export type COURSE_QUERY_RESULT = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level?: "advanced" | "beginner" | "intermediate";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor: {
    _id: string;
    _type: "instructor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    expertise?: Array<string>;
    bio?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | null;
  category: {
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  } | null;
  modules: Array<{
    _key: string;
    _type: "module";
    title?: string;
    summary?: string;
    lessons: Array<{
      _id: string;
      _type: "lesson";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      videoUrl?: string;
      thumbnail?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      duration?: number;
      freePreview?: boolean;
      studentCount?: number;
      notes?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          }
      >;
      keyPoints?: Array<string>;
      proTip?: string;
      resources?: Array<
        {
          _key: string;
        } & Resource
      >;
    }> | null;
  }> | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: LESSON_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    ...,    "course": *[_type == "course" && references(^._id)][0] {      title,      "slug": slug.current    }  }
export type LESSON_QUERY_RESULT = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
  course: {
    title: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: INSTRUCTOR_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    ...,    "courses": *[_type == "course" && instructor._ref == ^._id] {      title,      "slug": slug.current,      coverImage    }  }
export type INSTRUCTOR_QUERY_RESULT = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  courses: Array<{
    title: string | null;
    slug: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: SEARCH_QUERY
// Query: {    "lessons": *[_type == "lesson" && (title match $term || pt::text(notes) match $term)] {      _id,      _type,      title,      "slug": slug.current,      "course": *[_type == "course" && references(^._id)][0] {        title,        "slug": slug.current      }    },    "videoMoments": *[_type == "video" && (chapters[].label match $term || chunks[].text match $term)] {      _id,      _type,      url,      "lesson": *[_type == "lesson" && videoUrl == ^.url][0] {        title,        "slug": slug.current,        "course": *[_type == "course" && references(^._id)][0] {          title,          "slug": slug.current        }      },      "matchedChapters": chapters[label match $term],      "matchedChunks": chunks[text match $term]    }  }
export type SEARCH_QUERY_RESULT = {
  lessons: Array<{
    _id: string;
    _type: "lesson";
    title: string | null;
    slug: string | null;
    course: {
      title: string | null;
      slug: string | null;
    } | null;
  }>;
  videoMoments: Array<{
    _id: string;
    _type: "video";
    url: string | null;
    lesson: {
      title: string | null;
      slug: string | null;
      course: {
        title: string | null;
        slug: string | null;
      } | null;
    } | null;
    matchedChapters: Array<
      {
        _key: string;
      } & VideoChapter
    > | null;
    matchedChunks: Array<
      {
        _key: string;
      } & VideoChunk
    > | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    category->{ title, "slug": slug.current },\n    instructor->{ name, "slug": slug.current, photo }\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    ...,\n    instructor->,\n    category->,\n    modules[] {\n      ...,\n      lessons[]-> {\n        ...,\n      }\n    }\n  }\n': COURSE_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    ...,\n    "course": *[_type == "course" && references(^._id)][0] {\n      title,\n      "slug": slug.current\n    }\n  }\n': LESSON_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    ...,\n    "courses": *[_type == "course" && instructor._ref == ^._id] {\n      title,\n      "slug": slug.current,\n      coverImage\n    }\n  }\n': INSTRUCTOR_QUERY_RESULT;
    '\n  {\n    "lessons": *[_type == "lesson" && (title match $term || pt::text(notes) match $term)] {\n      _id,\n      _type,\n      title,\n      "slug": slug.current,\n      "course": *[_type == "course" && references(^._id)][0] {\n        title,\n        "slug": slug.current\n      }\n    },\n    "videoMoments": *[_type == "video" && (chapters[].label match $term || chunks[].text match $term)] {\n      _id,\n      _type,\n      url,\n      "lesson": *[_type == "lesson" && videoUrl == ^.url][0] {\n        title,\n        "slug": slug.current,\n        "course": *[_type == "course" && references(^._id)][0] {\n          title,\n          "slug": slug.current\n        }\n      },\n      "matchedChapters": chapters[label match $term],\n      "matchedChunks": chunks[text match $term]\n    }\n  }\n': SEARCH_QUERY_RESULT;
  }
}
